### PR TITLE
WIP Cedille archive with dependencies

### PR DESCRIPTION
**Pull request by CarlOlson**
Still working on this pull request, but I'd appreciate some early feedback on the Agda code. I'm still unsure of the correct style or source organization.

### CODE REVIEW

**Comment by astump** [comment]
Hi, Carl.

If Colin (McDonald, CC'ed) has a minute, he would be a good person to look
at this one, as he did a lot of work on the interaction between the
frontend and backend.

Aaron

**Comment by CarlOlson** [comment]
@HerbertMcSnout Any suggestions?

**Comment by HerbertMcSnout** [comment]
Sorry for the late reply!
For efficiency—though I doubt it _really_ matters for this fairly lightweight operation—I think it should first check if the file in `allDependencies-h` is already in the `trie` of results, and if so, don't add its dependencies to the list of files to pull more dependencies from? Two cousin files could share an imported file, and the current `allDependencies-h` would needlessly traverse the dependencies of the imported file twice, as there would be two separate instances where it in turn would be imported. Also, this is a bit nit-picky, but when the data in a `trie` doesn't matter, we by default just use a `stringset` (which is actually just `trie T`, where `T` is the top type). So maybe something like this(?):

`allDependencies-h : toplevel-state → stringset → 𝕃 string → 𝕃 string
allDependencies-h s t (filename :: filenames) with stringset-contains t filename | get-include-elt-if s filename
...| ff | just ie = allDependencies-h s (stringset-insert t filename) (filenames ++ include-elt.deps ie)
...| _ | _ = allDependencies-h s (stringset-insert t filename) filenames
allDependencies-h s t [] = stringset-strings t`

**Comment by CarlOlson** [comment]
Thanks for the feedback! I'll look into making those changes. I'm glad to see the `stringset`, I tried using `trie T` but wasn't sure what value to give it.

**Pull request closed without merging**
