### PR TITLE
IAL submodule and bootstrap script

### PR DESCRIPTION
**Pull request by CarlOlson**
These are some changes I made while getting it to work on Kubuntu and OSX. IAL is made a submodule, I think this is easier for most people. I also added a bootstrap script. To setup the project is now this easy:

```sh
./script/bootstrap
cabal exec make
```

The bootstrap script would be a good step towards adding CI.

Thoughts?

### CODE REVIEW

**Comment by cwjnkins** [comment]
@CarlOlson Thanks for this PR! I'll be sure to discuss it with the rest of the team today. One small thing -- could you change the submodule URL from the absolute `git@github.com:cedille/ial.git` to the relative `../ial.git`? Some of us on the team (myself in included) use HTTPS rather than SSH, and at any rate we want people who use either authentication method to be able to build Cedille as easily as possible. I can confirm that this single change made the whole build process go smoothly for me on a clean clone.

(See the [gist here](https://gist.github.com/cwjnkins/46b3102957b07bc733ee6c66d5287106) for a patch to apply)

**Comment by CarlOlson** [comment]
@cwjnkins I didn't even know you could use relative paths! 👍

**Comment by CarlOlson** [comment]
Good suggestion, I'll make that change tonight. You need `cabal exec make` if you install alex, happy, and cpphs from cabal. At least for me (on Kubuntu and OSX), I didn't get those added to my path. It probably applies more to students and CI where those won't already be installed.

**Comment by CarlOlson** [comment]
Are we good to merge?

**Pull request merged**
