### PR TITLE
Hole synthesis

### PR DESCRIPTION
**Pull request by pedrotst**
This pull request is the first steps towards Program by Refinement #27 

It will synthesize the correct lambdas of a hole.

In order to use it simply select a hole and press l

### CODE REVIEW

**Comment by pedrotst** [comment]
Turns out I forgot we could have parenthesized types. Which means that if you have a type that needs parenthesis weird things are going to happen.

I'll let you guys decide if you want to merge this "partial" work or if you'll prefer to wait for me to fix that.

**Comment by cwjnkins** [comment]
Hi @pedrotst, thanks for this PR. I've taken a look at the committed changes and I'm seeing that you're attempting to implement the feature using regular expressions. In addition to the issue you just mentioned, it looks like this code breaks even on something like foo : Nat -> Nat, or something that uses erased (non-dependent) arrows, or something that returns an intersection type where one of the components has a function type.

I think that a feature like this is best implemented using the back-end. This makes it more robust to the issues above, more maintainable, and more extensible (we may one day want to extend it to introduce intersections or trivially true equalities, or even consider some form of proof search)

**Comment by pedrotst** [comment]
Yeah, I was clearly hasty to open this pull request in the sense that there are some rough edges here and there that should be polished.

I don't quite get the argument about the back end though, could you please elaborate? Which backend functions in particular do you have in mind?

**Comment by cwjnkins** [comment]
I'm referring to functions such as those found in https://github.com/cedille/cedille/blob/master/src/interactive-cmds.agda . Implementing this in the back-end means you can work with the AST of types and terms directly, meaning there's more structure and information to work with than using a pure text-based approach. Thus it could be more easily extended and reused if we wanted to make this the first step in implementing commands that goal refinment by a function (like Agda), proof search, or other fancy tricks based on the meaning of the types or the local and global context. You also wouldn't have to re-implement fresh name generation, or worry about fiddly details since we already have a pretty printer in the backend.

**Comment by pedrotst** [comment]
I see. Makes a lot of sense.

In fact I considered the fact that I would have to go to the backend if I wanted to do some fancier synthesis. But since I would have to dive into the backend for such a small task I thought it would be a premature optimization, which we know to be the root of all evil (https://stackify.com/premature-optimization-evil/).

Anyways I'll fix these issues raised by still using regexes and then start reimplementing it in the backend. Since the reimplementation will probably take more than a couple of days, I'll let you guys decide whether to accept this pull request with regexes or not.

**Comment by pedrotst** [comment]
Everything discussed above should work now

**Comment by pedrotst** [comment]
Everything discussed here should work now.

**Comment by cwjnkins** [comment]
After discussing this PR we have unfortunately decided we must reject it. We appreciate the effort you've put in to making progress towards issue #27, but we realized this issue is not yet actionable. Some of the issues we create serve as reminders of features we want to revisit later, and for #27 we have not yet decided upon the best way to architect its implementation -- we still need to discuss this internally, but we do not feel that implementing it in the front-end is the way we want to proceed.

Going forward, we plan on adding a "CONTRIBUTIONS" file describing the best practices for improving the Cedille tool, which will include advice for contributors to first comment on an issue with a proposed solution so that we can discuss this and provide feedback before time is sunk into its implementation, and perhaps adding tags for issues where a proposal has been worked out and is ready to be worked on to make it easier for someone looking to help out the project.

**Pull request closed without merging**
