### PR TITLE
View Spans in an Archive

### PR DESCRIPTION
**Pull request by CarlOlson**
What?
- Ability to view a span's information in HTML
- CSS styling for better user experience

This should make the archival feature useful now. I think the next best thing to work on is exporting dependencies with archival.

### CODE REVIEW

**Comment by cwjnkins** [comment]
I just tested this out and it seems to work very well, especially viewing span information on click. Nice job!

We would probably want to do some filtering on the attributes listed -- no need to show the reader the start and end character position for each span -- but perhaps that's something for us to work on rather than asking you to? I'll wait for @astump 's input.

**Comment by CarlOlson** [comment]
Should I merge this? @astump

**Comment by astump** [comment]
I merged it in now (did not have a chance to test, but very excited to check it out).

**Comment by CarlOlson** [comment]
Ah, did you enter navigation mode yet? It doesn't update the span information before exporting. I'll probably add the in the next PR.

**Comment by cwjnkins** [comment]
@astump You may need to delete your compiled *.elc code, re-compile, then restart Emacs to reload cedille-mode. That's what I had to do, at any rate.

Fair warning, on my machine at least the elisp byte compilation seems to be a bit broken and requires manually re-compiling some of the modules. If you get any messages about invalid functions, ping me and I can help sort it out (as well as make an issue for it-- not sure at this time whether it's just my machine or not).

**Comment by cwjnkins** [comment]
Actually I think you *must* force recompile the elisp code as this PR only changes the HMTL, which from my very basic understanding of the cedille-archive code bakes-in the HTML template to the compiled elisp code. So make won't notice that anything has changed.

@CarlOlson Perhaps cedille-mode/cedille-mode-archive-template.html should be a dependency of target `elisp' in the Makefile?

**Pull request merged**
